workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

include: 'https://gitlab.com/nomadic-labs/gitlab-ocaml-ci-example/-/raw/main/.gitlab-ci.yml'

.build-matrix:
  before_script:
    - sudo apt-get update
    - sudo apt-get install --yes libgmp-dev
    - sudo apt-get install --yes nodejs
  parallel:
    matrix:
    - OCAML_COMPILER: ["4.10.2", "4.11.2", "4.12.1", "4.13.1", "4.14.1", "5.0.0"]
      DUNE_BUILD_TARGETS: "@src/all"
      DUNE_TEST_TARGETS: "@runtest @runtest_js"
      DUNE_DOC_TARGETS: [""]
    - OCAML_COMPILER: "4.14.1"
      DUNE_BUILD_TARGETS: [""]
      DUNE_TEST_TARGETS: "@fmt"
      DUNE_DOC_TARGETS: "@doc"

variables:
  CLEAN_OPAM_CACHE: "false"
  CLEAN_DUNE_CACHE: "false"
