---

test-docker:
  image: "${CI_REGISTRY}/tezos/docker-images/ci-docker:v1.6.0"
  script:
    - git clone https://gitlab.com/tezos/tezos.git --depth 1
    - cd tezos
    - apk add patch
    - ./scripts/patch-yes_node.sh
    - . ./scripts/version.sh
    - docker pull octezdevops/rust-toolchain
    - ./scripts/create_docker_image.sh tezos- latest registry.gitlab.com/tezos/opam-repository $opam_repository_tag "$(cat script-inputs/released-executables)" "$(git rev-parse --short HEAD)" without-evm-artifacts rust-toolchain latest
