#!/bin/sh

set -e

# shellcheck disable=SC1091
. /usr/share/debconf/confmodule

for s in baker accuser; do
  for p in active next; do
    # Check if the daemon is active before stopping it
    if systemctl is-active --quiet "mavkit-$s-$p.service"; then
      # Set a flag in a temporary file to indicate the daemon was running
      echo "1" > "/var/lib/mavkit-baker/$s-$p-daemon_was_running"
      echo "Stopping mavkit-$s-$p"
      sudo systemctl stop "mavkit-$s-$p.service"
    fi
  done
done
