.TH MAVKIT-SIGNER 1 "January 2024" "Mavkit Signer Manual"

.SH NAME
mavkit-signer \- Mavkit Remote signer

.SH SYNOPSIS
.B mavkit-signer
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B mavkit-signer
 provides the essential tools and functionalities for securely signing
 transactions, blocks, and other protocol-related data within the Tezos
 network.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Mavkit Documentation: https://protocol.mavryk.org/shell/cli-commands.html

.SH AUTHOR
Nomadic Labs.

.SH COPYRIGHT
Copyright \(co 2024 Nomadic Labs.

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
