.TH MAVKIT-BAKER 1 "January 2024" "Mavkit Baker Manual"

.SH NAME
mavkit-baker \- Mavkit Baker Daemon

.SH SYNOPSIS
.B mavkit-baker
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B mavkit-baker
includes the necessary tools and functionalities for participating in the
baking process, such as block creation, endorsement, and protocol-specific
consensus mechanisms.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Mavkit Documentation: https://protocol.mavryk.org/shell/cli-commands.html

.SH AUTHOR
Nomadic Labs.

.SH COPYRIGHT
Copyright \(co 2024 Nomadic Labs.

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
