.TH MAVKIT-CLIENT 1 "January 2024" "Mavkit Client Manual"

.SH NAME
mavkit-client \- Mavkit Command Line Interface

.SH SYNOPSIS
.B mavkit-client
[\fIOPTION\fR]... \fI<command>\fR [\fIARGS\fR]...

.SH DESCRIPTION
.B mavkit-client
is the command line interface for interacting with the Mavkit blockchain.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information.

.TP
.B \-\-version
Display version information.

.SH SEE ALSO
Online Mavkit Documentation: https://protocol.mavryk.org/shell/cli-commands.html

.SH AUTHOR
Nomadic Labs.

.SH COPYRIGHT
Copyright \(co 2024 Nomadic Labs.

.SH BUGS
Report bugs to: https://gitlab.com/tezos/tezos/-/issues
