[package]
name = "mir"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
lalrpop-util = "0.20.0"
checked = "0.5"
thiserror = "1.0"
logos = "0.13"
hex = "0.4"
tezos_crypto_rs = "0.5"
typed-arena = "2"
base58 = "0.2"
cryptoxide = "0.4"
num-bigint = "0.3"
num-integer = "0.1.46"
num-traits = "0.2"
chrono = { version = "0.4", default-features = false }
integer-sqrt = "0.1"
blst = "0.3"
bitvec = "1.0"
strum = "0.25"
strum_macros = "0.25"
smallvec = { version = "1.11", features = [ "const_new" ] }

[dev-dependencies]
proptest = "1.3.1"

[[bin]]
name = "tzt_runner"
path = "tzt_runner/main.rs"
