# SPDX-FileCopyrightText: 2022-2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "mavryk-smart-rollup-debug"
edition = "2021"
version = "0.2.2"
license = "MIT"
authors = [
    "TriliTech <contact@trili.tech>",
    "Mavryk Dynamics <info@mavryk.io>"
]
repository = "https://gitlab.com/mavryk-network/mavryk-protocol.git"
description = "Output formatted messages to Mavryk Smart Rollup debug log."
keywords = ["mavryk", "smart", "rollup"]
categories = ["no-std", "no-std::no-alloc", "api-bindings", "wasm"]

[dependencies.mavryk-smart-rollup-core]
path = "../core"
version = "0.2.2"

[dependencies.mavryk-smart-rollup-host]
path = "../host"
version = "0.2.2"
default-features = false

[features]
default = ["alloc"]
alloc = []
testing = ["mavryk-smart-rollup-core/testing"]
proto-alpha = ["mavryk-smart-rollup-core/proto-alpha", "mavryk-smart-rollup-host/proto-alpha"]
