---

# General setup
default:
  interruptible: true

# Basic configuration to guard against double-pipelines
workflow:
  rules:
    # This workflow entry allows pipelines for schedules events in which case it checks the
    # TZ_SCHEDULE_KIND which must be set in the pipeline scheduling interface
    # In either case it sets the TZ_PIPELINE_KIND variable to allow jobs to
    # selectively run on some pipelines but not all.
    # See https://docs.gitlab.com/ee/ci/yaml/README.html#workflow for additional
    # details.
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $TZ_SCHEDULE_KIND == "EXTENDED_TESTS"'
      variables:
        TZ_PIPELINE_KIND: "SCHEDULE"
      when: always
    # Switch between branch pipelines and merge request pipelines.
    # https://docs.gitlab.com/13.12/ee/ci/yaml/README.html#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # This workflow entry allows pipelines for push events (including force-push, push of fixup commits, rebase, etc.)
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - when: never # default

# The "manual" stage exists to fix a UI problem that occurs when mixing
# manual and non-manual jobs.
stages:
  - sanity
  - build
  - test
  - test_coverage
  - packaging
  - doc
  - build_release
  - publish_release
  - manual

# All the jobs belonging to a stage X should be in
# .gitlab/ci/X.yml. The stage "manual" is an exception to this rule,
# as jobs of that stage are not logically related.

# If the configuration for stage X is long, it can be broken up in
# subfiles .gitlab/ci/X/a.yml, .gitlab/ci/X/b.yml, etc (see e.g. the
# stage test).

# Finally, templates shall not be defined in one stage file and used
# in another. That is, a template defined in test.yml shall not be
# used in doc.yml (but it's fine to use it in a subfile test/X.yml).

include:
  # Actual jobs are defined in these included files
  - .gitlab/ci/templates.yml
  - .gitlab/ci/job_templates.yml

  - local: .gitlab/ci/pl-others.yml
    rules:
    - if: '($CI_COMMIT_REF_NAME == "test-latest-release" && $CI_PROJECT_NAMESPACE == "nomadic-labs") || ($CI_COMMIT_REF_NAME == "latest-release" && $CI_PROJECT_NAMESPACE == "tezos")'
      when: never
    - if: '($CI_COMMIT_BRANCH =~ /v[0-9]{1,3}-release$/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /v[0-9]{1,3}-release$/) && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - when: always

  # 'latest-release' and 'test-latest-release' branches
  - local: .gitlab/ci/pl-latest-release.yml
    rules:
    - if: '($CI_COMMIT_REF_NAME == "test-latest-release" && $CI_PROJECT_NAMESPACE == "nomadic-labs") || ($CI_COMMIT_REF_NAME == "latest-release" && $CI_PROJECT_NAMESPACE == "tezos")'
      when: always
    - if: '($CI_COMMIT_BRANCH =~ /v[0-9]{1,3}-release$/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /v[0-9]{1,3}-release$/) && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_NAMESPACE == "tezos" && ($CI_COMMIT_BRANCH = "master" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME = "master")'
      when: never
    - when: never

  # 'vX.Y-release' branches
  - local: .gitlab/ci/pl-release-branch.yml
    rules:
    - if: '($CI_COMMIT_REF_NAME == "test-latest-release" && $CI_PROJECT_NAMESPACE == "nomadic-labs") || ($CI_COMMIT_REF_NAME == "latest-release" && $CI_PROJECT_NAMESPACE == "tezos")'
      when: never
    - if: '($CI_COMMIT_BRANCH =~ /v[0-9]{1,3}-release$/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /v[0-9]{1,3}-release$/) && $CI_PROJECT_NAMESPACE == "tezos"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_NAMESPACE == "tezos" && ($CI_COMMIT_BRANCH = "master" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME = "master")'
      when: never
    - when: never

  # master branch pipeline
  - local: .gitlab/ci/pl-master.yml
    rules:
    - if: '($CI_COMMIT_REF_NAME == "test-latest-release" && $CI_PROJECT_NAMESPACE == "nomadic-labs") || ($CI_COMMIT_REF_NAME == "latest-release" && $CI_PROJECT_NAMESPACE == "tezos")'
      when: never
    - if: '($CI_COMMIT_BRANCH =~ /v[0-9]{1,3}-release$/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /v[0-9]{1,3}-release$/) && $CI_PROJECT_NAMESPACE == "tezos"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_NAMESPACE == "tezos" && ($CI_COMMIT_BRANCH = "master" || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME = "master")'
      when: always
    - when: never
