[package]
name = "kernel-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.7.1"
derive_more = "0.99.17"

[dependencies.rvemu]
git = "https://github.com/vapourismo/rvemu.git"
branch = "pub-translate"
